name: Docker publish

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Convert Docker Hub username to lowercase
        id: lowercase-username
        run: |
          DOCKERHUB_USERNAME_LOWER=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=username::$DOCKERHUB_USERNAME_LOWER"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.lowercase-username.outputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image tags
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            "${{ github.repository_owner | lower }}/${{ github.event.repository.name }}:latest"
            "${{ github.repository_owner | lower }}/${{ github.event.repository.name }}:${{ github.ref_name }}"
